### ISSUE TITLE
Atualização automática de Folowers sem deslogar e logar denovo

### ISSUE THREAD

**Issue by Henriquesoto92** [ziin/octodevs#1]
ideia de melhoria no titulo.

**Comment by ziin** [comment]
> 

Bem notado Henrique!

Atualmente já existem duas soluções para evitar que as informações dos profiles permaneçam obsoletas.
Uma delas foi a que você descobriu. No entanto, só irá funcionar entre 10 em 10 minutos, isso é para evitar spamming.
A outra solução é checar todos os profiles desatualizados nas últimas 24h quando uma nova requisição é feita, nesse caso, todos os profiles desatualizados serão atualizados em background, enquanto o usuário vê uma versão cacheada que será atualizada quando a atualização terminar.

Creio que essa solução irá funcionar enquanto o número de profiles não for muito grande.

Muito obrigado!
